//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadi.pk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public string Height_education { get; set; }
        public string Work_with { get; set; }
        public string Job_Role { get; set; }
        public string Income { get; set; }
        public Nullable<int> R_id { get; set; }
    
        public virtual tbl_Registration tbl_Registration { get; set; }
    }
}
