//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudappwithwebapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int ID { get; set; }
        public string St_Name { get; set; }
        public string St_Gender { get; set; }
        public string St_Desination { get; set; }
        public Nullable<long> St_salary { get; set; }
        public string St_Adress { get; set; }
    }
}
