//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoiceTable
    {
        public int CustomerInvoiceID { get; set; }
        public int CustomerID { get; set; }
        public int User_ID { get; set; }
        public string InvoiceNo { get; set; }
        public string Tittle { get; set; }
        public double TotalAmount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Decription { get; set; }
    }
}
