//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTable
    {
        public int Customer_ID { get; set; }
        public string Cus_Name { get; set; }
        public string Cus_Address { get; set; }
        public int Cus_Contact { get; set; }
        public string Area { get; set; }
        public string Decription { get; set; }
    }
}
