//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoiceDetailsTable
    {
        public int CustomerInvoiceDetailID { get; set; }
        public int CustomerInvoice_ID { get; set; }
        public int Product_ID { get; set; }
        public int SaleQty { get; set; }
        public int SaleUnitPrice { get; set; }
    }
}
