//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inventory_Management_systemEntities : DbContext
    {
        public Inventory_Management_systemEntities()
            : base("name=Inventory_Management_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTable> CategoryTables { get; set; }
        public virtual DbSet<Check> Checks { get; set; }
        public virtual DbSet<CustomerInvoiceDetailsTable> CustomerInvoiceDetailsTables { get; set; }
        public virtual DbSet<CustomerInvoiceTable> CustomerInvoiceTables { get; set; }
        public virtual DbSet<CustomerPaymentTable> CustomerPaymentTables { get; set; }
        public virtual DbSet<CustomerTable> CustomerTables { get; set; }
        public virtual DbSet<PurchaseTable> PurchaseTables { get; set; }
        public virtual DbSet<ShopStockTable> ShopStockTables { get; set; }
        public virtual DbSet<SupplierInvoiceDetailsTable> SupplierInvoiceDetailsTables { get; set; }
        public virtual DbSet<SupplierInvoiceTable> SupplierInvoiceTables { get; set; }
        public virtual DbSet<SupplierPaymentTable> SupplierPaymentTables { get; set; }
        public virtual DbSet<SupplierTable> SupplierTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<WereHouseStockTable> WereHouseStockTables { get; set; }
        public virtual DbSet<Customer_Sales> Customer_Sales { get; set; }
    }
}
