//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseTable()
        {
            this.SupplierInvoiceTables = new HashSet<SupplierInvoiceTable>();
            this.SupplierPaymentTables = new HashSet<SupplierPaymentTable>();
        }
    
        public int Sup_Invoice_ID { get; set; }
        public string Product_Name { get; set; }
        public int User_ID { get; set; }
        public int Suplier_ID { get; set; }
        public int Qty { get; set; }
        public Nullable<System.DateTime> Dateofmanufacture { get; set; }
        public Nullable<System.DateTime> Dateofexpiry { get; set; }
        public double Product_unit_price { get; set; }
        public double Total { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual CategoryTable CategoryTable { get; set; }
        public virtual SupplierTable SupplierTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierInvoiceTable> SupplierInvoiceTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPaymentTable> SupplierPaymentTables { get; set; }
    }
}
