//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopStockTable
    {
        public int ProductID { get; set; }
        public int Category_ID { get; set; }
        public int User_ID { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public double SaleunitPrice { get; set; }
        public double CurrentPurchaseUnitPrice { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public string Description { get; set; }
    }
}
