//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvoiceTable
    {
        public int SupplierInvoiceID { get; set; }
        public int Supplier_ID { get; set; }
        public int User_ID { get; set; }
        public int Invoice_No { get; set; }
        public string Tittle { get; set; }
        public double TotalAmount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Description { get; set; }
    
        public virtual PurchaseTable PurchaseTable { get; set; }
        public virtual SupplierTable SupplierTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
