//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvoiceDetailsTable
    {
        public int SupplierInvoiceDetailsID { get; set; }
        public int SupplierInvoice_ID { get; set; }
        public int Product_ID { get; set; }
        public int PuchaseQty { get; set; }
        public double PuchaseUnitPrice { get; set; }
    }
}
