//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPaymentTable
    {
        public int SupplierpaymentID { get; set; }
        public int Supplier_ID { get; set; }
        public int SupplierInvoice_ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public double TotalAmount { get; set; }
        public double PaymentAmount { get; set; }
        public double RemainingBalance { get; set; }
    
        public virtual PurchaseTable PurchaseTable { get; set; }
    }
}
