//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icecreamepalourmanagementsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flavour
    {
        public int fla_ID { get; set; }
        public string fla_Name { get; set; }
        public string fla_Ingredients { get; set; }
        public string fla_Procedure { get; set; }
        public string fla_Decription { get; set; }
        public string fla_Images { get; set; }
    }
}
