//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icecreamepalourmanagementsystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbicecreamepalourEntities : DbContext
    {
        public dbicecreamepalourEntities()
            : base("name=dbicecreamepalourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<FeeBack> FeeBacks { get; set; }
        public virtual DbSet<Flavour> Flavours { get; set; }
        public virtual DbSet<Oder> Oders { get; set; }
        public virtual DbSet<orderDetail> orderDetails { get; set; }
        public virtual DbSet<ReciepePayment> ReciepePayments { get; set; }
        public virtual DbSet<recipy> recipies { get; set; }
        public virtual DbSet<Subscriptionspayment> Subscriptionspayments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblSubscription> tblSubscriptions { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
    }
}
