//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icecreamepalourmanagementsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipy()
        {
            this.ReciepePayments = new HashSet<ReciepePayment>();
        }
    
        public int recipies_id { get; set; }
        public string Name { get; set; }
        public string images { get; set; }
        public string Ingredients { get; set; }
        public string procedure { get; set; }
        public string Description { get; set; }
        public Nullable<int> userId { get; set; }
        public string Publish_date { get; set; }
        public int Reciepe_type { get; set; }
        public double Fee { get; set; }
        public bool Isselect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciepePayment> ReciepePayments { get; set; }
        public virtual tbluser tbluser { get; set; }
    }
}
