//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icecreamepalourmanagementsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciepePayment
    {
        public int ReciepePaymentId { get; set; }
        public int userId { get; set; }
        public int recipies_id { get; set; }
        public string Date { get; set; }
        public string Card_No { get; set; }
        public double Fee { get; set; }
    
        public virtual recipy recipy { get; set; }
        public virtual tbluser tbluser { get; set; }
    }
}
